#scd parameter
#[column 1]	sele1: "select lauricAcid.0",	sele2: "select lauricAcid.1",	sele3: "select lauricAcid.2"
#[column 2]	sele1: "select lauricAcid.1",	sele2: "select lauricAcid.2",	sele3: "select lauricAcid.3"
#[column 3]	sele1: "select lauricAcid.2",	sele2: "select lauricAcid.3",	sele3: "select lauricAcid.4"
#[column 4]	sele1: "select lauricAcid.3",	sele2: "select lauricAcid.4",	sele3: "select lauricAcid.5"
#[column 5]	sele1: "select lauricAcid.4",	sele2: "select lauricAcid.5",	sele3: "select lauricAcid.6"
#[column 6]	sele1: "select lauricAcid.5",	sele2: "select lauricAcid.6",	sele3: "select lauricAcid.7"
#[column 7]	sele1: "select lauricAcid.6",	sele2: "select lauricAcid.7",	sele3: "select lauricAcid.8"
#[column 8]	sele1: "select lauricAcid.7",	sele2: "select lauricAcid.8",	sele3: "select lauricAcid.9"
#[column 9]	sele1: "select lauricAcid.8",	sele2: "select lauricAcid.9",	sele3: "select lauricAcid.10"
#[column 10]	sele1: "select lauricAcid.9",	sele2: "select lauricAcid.10",	sele3: "select lauricAcid.11"
-0.214159	-0.239874	-0.250558	-0.250114	-0.261259	-0.259132	-0.261636	-0.262688	-0.250068	-0.257035	
